name: Deploy Javadoc

permissions:
  contents: write
  
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy javadoc to Github Pages
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target-folder: "doc" # The folder where the generated javadoc will be stored. Default is docs
          javadoc-branch: "javadoc" # The branch for the javadoc contents. By default gh-pages
          